// Generates an AI summary of a pull request's changes and writes it into the
// PR description between marker comments, leaving the rest of the body intact.
//
// Env (set by .github/workflows/pr-summary.yml):
//   ANTHROPIC_API_KEY, GITHUB_TOKEN, GITHUB_REPOSITORY, PR_NUMBER, BASE_REF
//   SUMMARY_MODEL  optional, defaults to claude-opus-5
//   DRY_RUN=1      local check: build the prompt and show the merged body
//                  without calling Claude or GitHub

import { execFileSync } from "node:child_process";
import { existsSync, readFileSync } from "node:fs";

const START = "<!-- ai-summary:start -->";
const END = "<!-- ai-summary:end -->";
const MODEL = process.env.SUMMARY_MODEL || "claude-opus-5";
// Keeps very large PRs affordable; truncation is stated in the prompt and the summary.
const MAX_DIFF_CHARS = 300_000;
const EXCLUDED = [":(exclude)pnpm-lock.yaml"];

const git = (...args) =>
  execFileSync("git", args, { encoding: "utf8", maxBuffer: 64 * 1024 * 1024 });

export function mergeSummary(body, section) {
  const block = `${START}\n${section.trim()}\n${END}`;
  const current = body ?? "";
  const start = current.indexOf(START);
  const end = current.indexOf(END);
  if (start !== -1 && end > start) {
    return current.slice(0, start) + block + current.slice(end + END.length);
  }
  return current.trim() ? `${current.trimEnd()}\n\n${block}` : block;
}

function collectChanges(base) {
  const range = `origin/${base}...HEAD`;
  const fullDiff = git("diff", range, "--", ".", ...EXCLUDED);
  const truncated = fullDiff.length > MAX_DIFF_CHARS;
  return {
    commits: git("log", "--no-merges", "--format=- %s", `origin/${base}..HEAD`).trim(),
    stat: git("diff", "--stat", range, "--", ".", ...EXCLUDED).trim(),
    diff: truncated ? fullDiff.slice(0, MAX_DIFF_CHARS) : fullDiff,
    truncated,
    requirements: existsSync("requirements.yaml")
      ? readFileSync("requirements.yaml", "utf8")
      : "",
  };
}

function buildPrompt({ commits, stat, diff, truncated, requirements }) {
  return [
    "Summarize this pull request for its description. Reviewers read it before the diff.",
    "",
    "Output GitHub-flavored markdown only, with these sections:",
    "### Summary — 2-4 sentences: what changed and why.",
    "### Changes — bullets grouped by area (e.g. UI, API client, tooling, docs); name key files.",
    "### Requirements — the requirement IDs (SCD-*) this PR implements, tests or changes, judged",
    "from requirements.yaml edits and `@req` annotations in the diff. Write \"None\" if there are none.",
    "### Review notes — risks, follow-ups or anything a reviewer should check. Omit if nothing notable.",
    "Be factual and specific; do not invent changes that are not in the diff.",
    truncated
      ? `\nThe diff was truncated to its first ${MAX_DIFF_CHARS} characters; say so under Review notes.`
      : "",
    "",
    `<commits>\n${commits || "(none)"}\n</commits>`,
    `<diffstat>\n${stat}\n</diffstat>`,
    requirements ? `<requirements_yaml>\n${requirements}\n</requirements_yaml>` : "",
    `<diff>\n${diff}\n</diff>`,
  ].join("\n");
}

async function summarize(prompt) {
  const { default: Anthropic } = await import("@anthropic-ai/sdk");
  const client = new Anthropic();
  const response = await client.beta.messages.create({
    model: MODEL,
    max_tokens: 16000,
    betas: ["server-side-fallback-2026-07-01"],
    fallbacks: "default",
    output_config: { effort: "medium" },
    messages: [{ role: "user", content: prompt }],
  });
  if (response.stop_reason === "refusal") {
    throw new Error(`Claude declined to summarize (${response.stop_details?.category ?? "unknown"})`);
  }
  const text = response.content
    .filter((block) => block.type === "text")
    .map((block) => block.text)
    .join("")
    .trim();
  if (!text) throw new Error(`Empty summary (stop_reason: ${response.stop_reason})`);
  return text;
}

async function github(path, init = {}) {
  const res = await fetch(`https://api.github.com${path}`, {
    ...init,
    headers: {
      Accept: "application/vnd.github+json",
      Authorization: `Bearer ${process.env.GITHUB_TOKEN}`,
      "X-GitHub-Api-Version": "2022-11-28",
      "Content-Type": "application/json",
    },
  });
  if (!res.ok) throw new Error(`GitHub ${init.method ?? "GET"} ${path}: ${res.status} ${await res.text()}`);
  return res.json();
}

async function main() {
  const base = process.env.BASE_REF || "main";
  const changes = collectChanges(base);
  const prompt = buildPrompt(changes);
  const footer = `\n\n<sub>Generated by ${MODEL} from the diff; refreshed on every push. Edit outside this section — it will be kept.</sub>`;

  if (process.env.DRY_RUN) {
    console.log(`Diff: ${changes.diff.length} chars${changes.truncated ? " (truncated)" : ""}`);
    console.log(`Prompt: ${prompt.length} chars\n--- prompt head ---\n${prompt.slice(0, 1500)}\n---`);
    const sample = "My own notes about this PR.";
    const once = mergeSummary(sample, "### Summary\nfirst run" + footer);
    const twice = mergeSummary(once, "### Summary\nsecond run" + footer);
    console.log(`--- merged body after two runs ---\n${twice}`);
    return;
  }

  const summary = await summarize(prompt);
  const path = `/repos/${process.env.GITHUB_REPOSITORY}/pulls/${process.env.PR_NUMBER}`;
  const pr = await github(path);
  await github(path, {
    method: "PATCH",
    body: JSON.stringify({ body: mergeSummary(pr.body, summary + footer) }),
  });
  console.log(`Updated description of PR #${process.env.PR_NUMBER}`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
